<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmployeeInformationSystem.Domain\EmployeeInformationSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Models\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
